services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    image: re-admin-assetpro
    container_name: re-admin-assetpro-app
    ports:
      - "8088:80"
    restart: unless-stopped
