// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhvmvypbnmpyuupiuhdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impodm12eXBibm1weXV1cGl1aGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODMzNjIsImV4cCI6MjA2OTI1OTM2Mn0.5VgmGiFMy8U-oFOqT0J33oPItsTwcYWFSFJBE3Wd1fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});